title: "ampatchlab/nf-typeHLA"
subtitle: "HLA typing Nextflow pipeline"
intro_text: False

report_header_info:
    - Contact E-mail: 'stephen.kazakoff@qimrberghofer.edu.au'
    - Application Type: 'HLA typing'

module_order:
    - fastqc:
        name: 'FastQC (raw)'
        anchor: 'fastqc-raw'
        target: 'FastQC'
        path_filters_exclude:
            - '*.trimmed_fastqc.zip'
    - cutadapt
    - fastqc:
        name: 'FastQC (trimmed)'
        anchor: 'fastqc-trimmed'
        target: 'FastQC'
        path_filters:
            - '*.trimmed_fastqc.zip'
    - picard
    - samtools
